name: publish

on:
  push:
    tags:
      - "v*"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Check
        run: cargo check

      # - name: Clippy  
      #   run: RUSTFLAGS="-Dwarnings" cargo clippy -- -D warnings

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Format
        run: cargo fmt --all -- --check

      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
